# Generated by Django 3.2 on 2024-01-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('comment', models.CharField(max_length=1000, verbose_name='comment')),
                ('photo', models.CharField(max_length=1000, verbose_name='photo')),
            ],
        ),
    ]
